on: 
  pull_request:
    branches: 
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Install Python Dependencies
      run: pip install -r ./src/backend/pubfinder/requirements.txt

    - name: Python Linter
      run: pylint src/backend/pubfinder/

    - name: API Unit Tests
      run: |
        cd src/backend/pubfinder
        python manage.py test

    - name: Install NPM Dependencies
      run: |
        cd ../../frontend
        pwd
