on: 
  pull_request:
    branches: 
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Install Python Dependencies
      run: pip install -r ./src/backend/pubfinder/requirements.txt

    - name: Python Linter
      run: pylint src/backend/pubfinder/

    - name: API Unit Tests
      run: |
        cd src/backend/pubfinder
        echo pwd
        python manage.py test

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        check-latest: true

    - name: Install NPM Dependencies
      run: |
        cd src/frontend
        npm ci

    - name: TypeScript Linter
      run: |
        cd src/frontend
        npx eslint .

    - name: React Tests
      run: |
        cd src/frontend
        npm run test 
